[build]
builder = "DOCKERFILE"
dockerfilePath = "/django/Dockerfile"
watchPatterns = [
    "/django/requirements.txt",
    "/django/src/**",
    "railway.toml",
    "/django/Dockerfile",
]

[deploy]
runtime = "UNSPECIFIED"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10